### ISSUE TITLE
I am unable to use the PR maker edition

### ISSUE THREAD

**Issue by pmario** [saqimtiaz/tw5-docs-pr-maker#7]
I am unable to use the PR maker edition -- Did you change something lately?

**Comment by pmario** [comment]
Not sure why. But it works now. changed Token and did some reloads

**Comment by saqimtiaz** [comment]
@pmario do you recall what the initial probem was? Nothing has been changed in a pretty long time.

**Comment by pmario** [comment]
I did have a look at the dev tools and it did return a 404 on the POST command. So the error was "not found". But there was not more info, **what** was "not found". 

Then I did create a new token and also did some browser reloads. I did run some more tests after 15 minutes and it seemed to work as expected again. May be a server problem somewhere
